name: InfoBook
version: 1.0
author: Crafter20162017
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11]
main: InfoBook\Main
description: Gives a book on command!
permissions:
 book.command:
  default: true
commands:
 core:
  description: §eHave access to §bSkyRealm§6Faction's§e Help Section!
